ALTER TABLE `accounts` ADD `SelectedBarrack` SMALLINT(6) NOT NULL DEFAULT 11;
ALTER TABLE `accounts` ADD `Medal` INT NOT NULL DEFAULT 0;
ALTER TABLE `accounts` ADD `GiftMedal` INT NOT NULL DEFAULT 0;
ALTER TABLE `accounts` ADD `PremiumMedal` INT NOT NULL DEFAULT 0;
ALTER TABLE `accounts` ADD `ReceiveGiftMedal` INT NOT NULL DEFAULT 0;
